Fix paging playground
Different version of annotations was being pulled in for the integration
test app vs its instrumented tests, which was causing them to fail to
build with:

GradleException: Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints:...

Test: cd paging && ./gradlew bOS
Change-Id: Ibb3339315975caab0ac5b7734400e8e13602aa36