[WebView Support Library] skip test on pre-L devices
This skips testShouldOverrideUrlLoadingDefault on pre-L devices, since
this test needs to instantiate a WebResourceRequest, which was defined
in API 21 (L). This avoids a NoClassDefFoundError error.

This change is not required for other test cases using
WebResourceRequest because most tests are guarded by feature checks,
which implies SDK_INT >= L.

Fixes: 110099649
Test: ./gradlew :webkit:connectedAndroidTest (on K device)
Change-Id: I7462ceb74711aa15f778cbe2c5d83d0d92ebaa75