Avoid comparing resource id's
Transition.java:1020: Error: Comparing resource types (@IdRes) other than equality
    is dangerous and usually wrong; some resource types set top bit which turns
    the value negative [ResourceType]
        if (targetId > 0) {
            ~~~~~~~~~~~~

Change-Id: I3c7ccbead333ba4322059bcff324deb28da25ee1
(cherry picked from commit fa7b4e1c1d73d96dc7bd45ec798c0382a1bdd3ef)