DO NOT MERGE) MediaRouter: Handle NoSuchMethodError at MediaRouterJellybeanMr1
android.media.MediaRouter.RouteInfo.getPresentationDisplay() was
added in API 17. However, some factory release of JB MR1 missed
this API. It can cause NoSuchMethodError when
android.support.v7.media.MediaRouter.getInstance() is called.

Bug: 26273371
Change-Id: If2e814afdd537697892a5867bb684e9d130ee8e2
(cherry picked from commit efaede921c8e400142d571edc3da156dc3853d5b)