Fix internal-testutils-kmp project sync (#827)
It fixes this error during IDE sync:
```
Failed to resolve platform dependency on jsTest
org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve project :internal-testutils-kmp.
Required by:
    project :compose:foundation:foundation
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of project :internal-testutils-kmp was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but: