Fix ATP timeout due to NoClassDefFoundError which is caused by CallbackToFutureAdapter class not found.
Somehow test build does not contains the latest class in concurrent-futures 1.0.0-alpha03.
change it to explicit 1.0.0-alpha03 version to fix the problem.

Bug: 130619889
Test: manual test.
Change-Id: I64588ec84b1a452a5ceae40a1ca6fab4c476c11a