Add flags to run Chrome with WebGL on CI (#2721)
Today the tests CI running in Chrome started to fail with such an error:
```
TypeError: Cannot read properties of undefined (reading 'getParameter') at <global>._glGetString(skiko.mjs:8)
``` 
We noticed that github runner got an updated Chrome version. But
downgrading didn't help.

So we set additional flags for Chrome launcher.


## Testing
N/A

## Release Notes
N/A