Pass context for calling IconCompat.toIcon
`androidx.core.graphics.drawable.IconCompat.toIcon()` is deprecated, we should avoid calling it in core lib to prevent the exception thrown like:

```
java.lang.IllegalArgumentException: Context is required to resolve the file uri of the icon: content://com.google.android.samples.socialite/icon/1
    at androidx.core.graphics.drawable.IconCompat$Api23Impl.toIcon(IconCompat.java:1297)
    at androidx.core.graphics.drawable.IconCompat.toIcon(IconCompat.java:529)
    at androidx.core.graphics.drawable.IconCompat.toIcon(IconCompat.java:517)
    at androidx.core.app.Person$Api28Impl.toAndroidPerson(Person.java:427)
    at androidx.core.app.Person.toAndroidPerson(Person.java:152)
    at androidx.core.app.NotificationCompatBuilder.<init>(NotificationCompatBuilder.java:263)
    at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:2531)
    at com.google.android.samples.socialite.repository.NotificationHelper.showNotification(NotificationHelper.kt:274)
    at com.google.android.samples.socialite.repository.NotificationHelper.showNotification$default(NotificationHelper.kt:159)
    at com.google.android.samples.socialite.repository.ChatRepository$sendMessage$2.invokeSuspend(ChatRepository.kt:92)
```

Test: ./gradlew :core:core:check
Change-Id: I9c3874ae91efbb382693f679cadad62a9cba4a83